### ISSUE TITLE
Plot Improvements in Replay

### ISSUE THREAD

**Issue by skalbfleisch** [NSLS-II/dataportal#138]
- [ ] NSLS-II/replay#15 The data should be plotted against the scanned motor by default, not time.
- [ ] NSLS-II/replay#16 The scan list in Replay should be a list rather than a selection via radio buttons
- [ ] NSLS-II/replay#17 A button in Replay to print a scan would be very helpful, also, a button to send it to olog together with some comments.
- [ ] NSLS-II/replay#18 There should be an option to set the upper and lower limit of the plotted axes.
- [x] #145 The scaling should be maintained when set manually and a new plot is selected.
- [ ] NSLS-II/replay#19 There should be an option to switch between linear and logarithmic scaling of the plotted axes.
- [ ] NSLS-II/replay#20 There should be an easy way to display multiple scans in one plot.
- [ ] NSLS-II/replay#21 There should be an option to display multiple scalars on multiple y axis of a scan in the same plot. Again, this setting should be maintained, when a new scan is selected.
- [ ] NSLS-II/replay#22 Scaling settings (range, log/linear, etc.)  of the axis should not be overwritten when automatic data update from muxer is activated.

[@ericdill edit] editing to link issues to original post

**Comment by tacaswell** [comment]
What do you mean by 'print a scan'?

I don't think mds currently has a notion of 'scanned' motor, everything is just a measurement.

If you mouse over the canvas and hit the 'L' key (lower-case, but looks too much like 1 (one) to type) it will switch the y-axis between linear and log.  If you enable the plot tool bar there is also a button which will bring up a dialog which will also let you control the same.

**Comment by ericdill** [comment]
I'm splitting these up into individual issues

**Comment by ericdill** [comment]
Moved to nsls-ii/replay#25
