### ISSUE TITLE
DataMuggler Master Issue

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/dataportal#28]
### Enhancements & Fixes
- [ ] Make downsampling work on nonscalar data.
- [x] Add `dm.plan.bin_*` functions, and revert to all values columns named `val`.
- [ ] Accept strings (`'mean'`) and functions (`lambda x: np.mean(x, 0)`) as upsampling and downsampling rules.
- [x] Allow replay to modify hard defaults of down- and upsampling for a given muggler instance.
- [x] Do interpolation at bin centers, ignoring `time_labels`. Remove anchoring code. Bin labels should just be integers.
- [x] Add a test and an example with nonscalar data, building on broker examples already in the repo.
- [x] If there is one value in a bin, use it (don't interpolate to the bin center).
- [ ] Add more `bin*` convenience methods.
- [x] In the output of `resample` and `bin*`, include multiple columns per data source, giving mean, std, etc. The user can ignore that information, but it should be shown by default. Per discussion with @ericdill.
- [x] Add method for extracting a '*_timestamp`column from a source's`timestamp`. Per our Tuesday afternoon discussion, this will be a data column like any other.
- [x] Handle events that carry more than one data source. That may or may not work currently. Test with an example, obviously.
### Optimizations
- [x] Cache the descptor id -- cheaper than checking every source on every event add.
## Long Term
- [x] Ability to restrict binning to desired columns, to avoid resampling the entire data set. This is important for keeping replay snappy.
- [ ] Once the [pandas IntervalIndex](https://github.com/pydata/pandas/pull/8707) feature is merged into master, it will offer a better way to represent binned data. (For the uninitiated, see this [short demo notebook](http://nbviewer.ipython.org/github/jreback/pydata2014-pandas/blob/master/notebooks/Intervals.ipynb).)
