### ISSUE TITLE
Wednesday Deployment Master Issue

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/dataportal#34]
- [x] MDS implementing agreed-upon names
- [x] MDS implementing required fields
- [x] MDS returning data as `(value, time)` not `{'value': ..., 'timestamp': ...}`
- [x] ophyd integration with new MDS
- [ ] critical broker functionality:
  - [ ] get events, including CA events, by time
  - [ ] get events, including CA events, associated with given header(s)
  - [ ] get headers by important properties like run_id, owner, etc
  - [ ] get last N headers
- [x] a working, current muggler example notebook
